server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  JwtSecretKey: secretKey
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  SSL: false
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUsername: postgres
  PostgresqlPassword: postgres
  PostgresqlDbName: news
  PostgresqlSslMode: false
  PgDriver: pgx

minio:
  Endpoint: 127.0.0.1:9000
  MinioAccessKey: minio
  MinioSecretKey: minio123
  UseSSL: false
  MinioEndpoint: http://127.0.0.1:9000
  Bucket: news

#aws:
#  Endpoint: play.min.io
#  MinioAccessKey: Q3AM3UQ867SPQQA43P2F
#  MinioSecretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
#  UseSSL: false
#  MinioEndpoint: http://127.0.0.1:9000



